In [1]:
import pandas as pd
import numpy as np

In [2]:
df_baseball = pd.read_csv("baseball.csv")
df_baseball

,W,R,AB,H,2B,3B,HR,BB,SO,SB,RA,ER,ERA,CG,SHO,SV,E
0,95,724,5575,1497,300,42,139,383,973,104,641,601,3.73,2,8,56,88
1,83,696,5467,1349,277,44,156,439,1264,70,700,653,4.07,2,12,45,86
2,81,669,5439,1395,303,29,141,533,1157,86,640,584,3.67,11,10,38,79
3,76,622,5533,1381,260,27,136,404,1231,68,701,643,3.98,7,9,37,101
4,74,689,5605,1515,289,49,151,455,1259,83,803,746,4.64,7,12,35,86
5,93,891,5509,1480,308,17,232,570,1151,88,670,609,3.80,7,10,34,88
6,87,764,5567,1397,272,19,212,554,1227,63,698,652,4.03,3,4,48,93
7,81,713,5485,1370,246,20,217,418,1331,44,693,646,4.05,0,10,43,77
8,80,644,5485,1383,278,32,167,436,1310,87,642,604,3.74,1,12,60,95
9,78,748,5640,1495,294,33,161,478,1148,71,753,694,4.31,3,10,40,97
10,88,751,5511,1419,279,32,172,503,1233,101,733,680,4.24,5,9,45,119
11,86,729,5459,1363,278,26,230,486,1392,121,618,572,3.57,5,13,39,85
12,85,661,5417,1331,243,21,176,435,1150,52,675,630,3.94,2,12,46,93
13,76,656,5544,1379,262,22,198,478,1336,69,726,677,4.16,6,12,45,94
14,68,694,5600,1405,277,46,146,475,1119,78,729,664,4.14,5,15,28,126
15,100,647,5484,1386,288,39,137,506,1267,69,525,478,2.94,1,15,62,96
16,98,697,5631,1462,292,27,140,461,1322,98,596,532,3.21,0,13,54,122
17,97,689,5491,1341,272,30,171,567,1518,95,608,546,3.36,6,21,48,111
18,68,655,5480,1378,274,34,145,412,1299,84,737,682,4.28,1,7,40,116
19,64,640,5571,1382,257,27,167,496,1255,134,754,700,4.33,2,8,35,90
20,90,683,5527,1351,295,17,177,488,1290,51,613,557,3.43,1,14,50,88
21,83,703,5428,1363,265,13,177,539,1344,57,635,577,3.62,4,13,41,90
22,71,613,5463,1420,236,40,120,375,1150,112,678,638,4.02,0,12,35,77
23,67,573,5420,1361,251,18,100,471,1107,69,760,698,4.41,3,10,44,90
24,63,626,5529,1374,272,37,130,387,1274,88,809,749,4.69,1,7,35,117
25,92,667,5385,1346,263,26,187,563,1258,59,595,553,3.44,6,21,47,75
26,84,696,5565,1486,288,39,136,457,1159,93,627,597,3.72,7,18,41,78
27,79,720,5649,1494,289,48,154,490,1312,132,713,659,4.04,1,12,44,86
28,74,650,5457,1324,260,36,148,426,1327,82,731,655,4.09,1,6,41,92
29,68,737,5572,1479,274,49,186,388,1283,97,844,799,5.04,4,4,36,95

In [3]:
df_baseball.shape

(30, 17)

In [4]:
df_baseball.columns

Index(['W', 'R', 'AB', 'H', '2B', '3B', 'HR', 'BB', 'SO', 'SB', 'RA', 'ER',
       'ERA', 'CG', 'SHO', 'SV', 'E'],
      dtype='object')

In [5]:
df_baseball.isnull().sum()

W      0
R      0
AB     0
H      0
2B     0
3B     0
HR     0
BB     0
SO     0
SB     0
RA     0
ER     0
ERA    0
CG     0
SHO    0
SV     0
E      0
dtype: int64

In [6]:
df_baseball.dtypes

W        int64
R        int64
AB       int64
H        int64
2B       int64
3B       int64
HR       int64
BB       int64
SO       int64
SB       int64
RA       int64
ER       int64
ERA    float64
CG       int64
SHO      int64
SV       int64
E        int64
dtype: object

# EDA

In [7]:
df_baseball.describe()

,W,R,AB,H,2B,3B,HR,BB,SO,SB,RA,ER,ERA,CG,SHO,SV,E
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.00000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,80.966667,688.233333,5516.266667,1403.533333,274.733333,31.300000,163.633333,469.100000,1248.20000,83.500000,688.233333,635.833333,3.956333,3.466667,11.300000,43.066667,94.333333
std,10.453455,58.761754,70.467372,57.140923,18.095405,10.452355,31.823309,57.053725,103.75947,22.815225,72.108005,70.140786,0.454089,2.763473,4.120177,7.869335,13.958889
min,63.000000,573.000000,5385.000000,1324.000000,236.000000,13.000000,100.000000,375.000000,973.00000,44.000000,525.000000,478.000000,2.940000,0.000000,4.000000,28.000000,75.000000
25%,74.000000,651.250000,5464.000000,1363.000000,262.250000,23.000000,140.250000,428.250000,1157.50000,69.000000,636.250000,587.250000,3.682500,1.000000,9.000000,37.250000,86.000000
50%,81.000000,689.000000,5510.000000,1382.500000,275.500000,31.000000,158.500000,473.000000,1261.50000,83.500000,695.500000,644.500000,4.025000,3.000000,12.000000,42.000000,91.000000
75%,87.750000,718.250000,5570.000000,1451.500000,288.750000,39.000000,177.000000,501.250000,1311.50000,96.500000,732.500000,679.250000,4.220000,5.750000,13.000000,46.750000,96.750000
max,100.000000,891.000000,5649.000000,1515.000000,308.000000,49.000000,232.000000,570.000000,1518.00000,134.000000,844.000000,799.000000,5.040000,11.000000,21.000000,62.000000,126.000000

In [8]:
from scipy.stats import zscore
z_score=abs(zscore(df_baseball))
print(df_baseball.shape)
df_baseball_final=df_baseball.loc[(z_score<3).all(axis=1)]
print(df_baseball_final.shape)

(30, 17)
(29, 17)

In [9]:
df_x=df_baseball.drop(columns=["W"])
y=df_baseball[["W"]]

In [10]:
df_x

,R,AB,H,2B,3B,HR,BB,SO,SB,RA,ER,ERA,CG,SHO,SV,E
0,724,5575,1497,300,42,139,383,973,104,641,601,3.73,2,8,56,88
1,696,5467,1349,277,44,156,439,1264,70,700,653,4.07,2,12,45,86
2,669,5439,1395,303,29,141,533,1157,86,640,584,3.67,11,10,38,79
3,622,5533,1381,260,27,136,404,1231,68,701,643,3.98,7,9,37,101
4,689,5605,1515,289,49,151,455,1259,83,803,746,4.64,7,12,35,86
5,891,5509,1480,308,17,232,570,1151,88,670,609,3.80,7,10,34,88
6,764,5567,1397,272,19,212,554,1227,63,698,652,4.03,3,4,48,93
7,713,5485,1370,246,20,217,418,1331,44,693,646,4.05,0,10,43,77
8,644,5485,1383,278,32,167,436,1310,87,642,604,3.74,1,12,60,95
9,748,5640,1495,294,33,161,478,1148,71,753,694,4.31,3,10,40,97
10,751,5511,1419,279,32,172,503,1233,101,733,680,4.24,5,9,45,119
11,729,5459,1363,278,26,230,486,1392,121,618,572,3.57,5,13,39,85
12,661,5417,1331,243,21,176,435,1150,52,675,630,3.94,2,12,46,93
13,656,5544,1379,262,22,198,478,1336,69,726,677,4.16,6,12,45,94
14,694,5600,1405,277,46,146,475,1119,78,729,664,4.14,5,15,28,126
15,647,5484,1386,288,39,137,506,1267,69,525,478,2.94,1,15,62,96
16,697,5631,1462,292,27,140,461,1322,98,596,532,3.21,0,13,54,122
17,689,5491,1341,272,30,171,567,1518,95,608,546,3.36,6,21,48,111
18,655,5480,1378,274,34,145,412,1299,84,737,682,4.28,1,7,40,116
19,640,5571,1382,257,27,167,496,1255,134,754,700,4.33,2,8,35,90
20,683,5527,1351,295,17,177,488,1290,51,613,557,3.43,1,14,50,88
21,703,5428,1363,265,13,177,539,1344,57,635,577,3.62,4,13,41,90
22,613,5463,1420,236,40,120,375,1150,112,678,638,4.02,0,12,35,77
23,573,5420,1361,251,18,100,471,1107,69,760,698,4.41,3,10,44,90
24,626,5529,1374,272,37,130,387,1274,88,809,749,4.69,1,7,35,117
25,667,5385,1346,263,26,187,563,1258,59,595,553,3.44,6,21,47,75
26,696,5565,1486,288,39,136,457,1159,93,627,597,3.72,7,18,41,78
27,720,5649,1494,289,48,154,490,1312,132,713,659,4.04,1,12,44,86
28,650,5457,1324,260,36,148,426,1327,82,731,655,4.09,1,6,41,92
29,737,5572,1479,274,49,186,388,1283,97,844,799,5.04,4,4,36,95

In [11]:
y

      W
0    95
1    83
2    81
3    76
4    74
5    93
6    87
7    81
8    80
9    78
10   88
11   86
12   85
13   76
14   68
15  100
16   98
17   97
18   68
19   64
20   90
21   83
22   71
23   67
24   63
25   92
26   84
27   79
28   74
29   68

In [12]:
from sklearn.preprocessing import MinMaxScaler
ms= MinMaxScaler()
x = ms.fit_transform(df_x)
x = pd.DataFrame(x,columns=df_x.columns)

# Modelling

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import linear_model
def maxr2_score(regr,x,y):
    max_r_score=0
    for r_state in range(42,100):
        x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=r_state,test_size=0.20)
        regr.fit(x_train,y_train)
        y_pred = regr.predict(x_test)
        r2_scr = r2_score(y_test,y_pred)
        print("r2 score corresponding to random state: ",r_state,"is: ",r2_scr)
        if r2_scr>max_r_score:
            max_r_score=r2_scr
            final_r_state=r_state 
    print("max r2 score corresponding to",final_r_state," is ",max_r_score)
    return final_r_state

In [14]:
from sklearn.linear_model import LinearRegression
lreg=LinearRegression()
r_state=maxr2_score(lreg,x,y)

r2 score corresponding to random state:  42 is:  0.7876400316149371
r2 score corresponding to random state:  43 is:  -1.0543428896603269
r2 score corresponding to random state:  44 is:  0.5894992447123899
r2 score corresponding to random state:  45 is:  0.6385651240924776
r2 score corresponding to random state:  46 is:  0.6261439472974548
r2 score corresponding to random state:  47 is:  0.8116559418363318
r2 score corresponding to random state:  48 is:  0.8234694071796749
r2 score corresponding to random state:  49 is:  -0.07399772649652081
r2 score corresponding to random state:  50 is:  0.6111709711670308
r2 score corresponding to random state:  51 is:  0.45827451765866034
r2 score corresponding to random state:  52 is:  0.5097793692109424
r2 score corresponding to random state:  53 is:  0.25500582067072197
r2 score corresponding to random state:  54 is:  0.7551746347340766
r2 score corresponding to random state:  55 is:  0.7860903369149688
r2 score corresponding to random state:  56 is:  0.6079899644109644
r2 score corresponding to random state:  57 is:  -0.7979271743714598
r2 score corresponding to random state:  58 is:  0.4104992306210067
r2 score corresponding to random state:  59 is:  0.008019457575929922
r2 score corresponding to random state:  60 is:  -0.41187977286946453
r2 score corresponding to random state:  61 is:  -0.11594360026658301
r2 score corresponding to random state:  62 is:  0.6185871131833667
r2 score corresponding to random state:  63 is:  0.5576984549179225
r2 score corresponding to random state:  64 is:  0.6352725305739728
r2 score corresponding to random state:  65 is:  0.724759815662091
r2 score corresponding to random state:  66 is:  0.17191346624768977
r2 score corresponding to random state:  67 is:  0.8087753828913783
r2 score corresponding to random state:  68 is:  0.8732463116865934
r2 score corresponding to random state:  69 is:  0.5242852201258346
r2 score corresponding to random state:  70 is:  -0.1935077561101155
r2 score corresponding to random state:  71 is:  0.3790991443798014
r2 score corresponding to random state:  72 is:  0.7102012570894078
r2 score corresponding to random state:  73 is:  0.7261324544604102
r2 score corresponding to random state:  74 is:  -2.006452499229126
r2 score corresponding to random state:  75 is:  0.3197089913026594
r2 score corresponding to random state:  76 is:  -0.5350831359882557
r2 score corresponding to random state:  77 is:  -0.39199159940340333
r2 score corresponding to random state:  78 is:  0.39264201587646297
r2 score corresponding to random state:  79 is:  0.258912806329022
r2 score corresponding to random state:  80 is:  -1.3881438676977087
r2 score corresponding to random state:  81 is:  -3.832495192183825
r2 score corresponding to random state:  82 is:  0.7619024479455518
r2 score corresponding to random state:  83 is:  0.8479393575196414
r2 score corresponding to random state:  84 is:  0.7098512965463363
r2 score corresponding to random state:  85 is:  0.8407963276845581
r2 score corresponding to random state:  86 is:  0.7404936612670716
r2 score corresponding to random state:  87 is:  0.30956962881374417
r2 score corresponding to random state:  88 is:  -4.229901909249004
r2 score corresponding to random state:  89 is:  -0.7798144825334639
r2 score corresponding to random state:  90 is:  0.8300294405682666
r2 score corresponding to random state:  91 is:  0.6922110717277735
r2 score corresponding to random state:  92 is:  0.5943186016078817
r2 score corresponding to random state:  93 is:  0.4203580279447403
r2 score corresponding to random state:  94 is:  -0.8652265962508607
r2 score corresponding to random state:  95 is:  0.5065497917815451
r2 score corresponding to random state:  96 is:  0.13466114454257838
r2 score corresponding to random state:  97 is:  0.8340143915795851
r2 score corresponding to random state:  98 is:  0.5691793123627691
r2 score corresponding to random state:  99 is:  0.8804448045510326
max r2 score corresponding to 99  is  0.8804448045510326

In [15]:
from sklearn.model_selection import cross_val_score
cross_val_score(linear_model.LinearRegression(),x,y,cv=5,scoring="r2").mean()

0.04075540667456088

In [16]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
lsreg=Lasso()
parameters={"alpha":[0.001,0.01,0.1,1]}
clf = GridSearchCV(lsreg, parameters, cv=5)
clf.fit(x,y)
clf.best_params_

/Users/vishaln/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.8280095751134553, tolerance: 0.27389583333333334
  positive)
/Users/vishaln/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1.8625460558266553, tolerance: 0.3039625
  positive)
/Users/vishaln/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1.6542621651743517, tolerance: 0.19896250000000001
  positive)
/Users/vishaln/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 21.853839373103206, tolerance: 0.24669583333333336
  positive)

{'alpha': 0.1}

In [17]:
lsreg=Lasso(alpha=1)
r_state=maxr2_score(lsreg,x,y)

r2 score corresponding to random state:  42 is:  0.44963437869973355
r2 score corresponding to random state:  43 is:  0.13811411142963004
r2 score corresponding to random state:  44 is:  0.4168776329553977
r2 score corresponding to random state:  45 is:  0.05465099626647785
r2 score corresponding to random state:  46 is:  0.3104384661735067
r2 score corresponding to random state:  47 is:  0.44543076185302044
r2 score corresponding to random state:  48 is:  0.4206497041078582
r2 score corresponding to random state:  49 is:  0.2766663615175672
r2 score corresponding to random state:  50 is:  0.22476955504717466
r2 score corresponding to random state:  51 is:  -0.2620927252955756
r2 score corresponding to random state:  52 is:  0.5020213130233377
r2 score corresponding to random state:  53 is:  -0.7308565457434737
r2 score corresponding to random state:  54 is:  0.42522339870492454
r2 score corresponding to random state:  55 is:  0.17127773340269614
r2 score corresponding to random state:  56 is:  0.5694559610613334
r2 score corresponding to random state:  57 is:  -0.22430152491493405
r2 score corresponding to random state:  58 is:  -0.557368044732613
r2 score corresponding to random state:  59 is:  0.21535497057082276
r2 score corresponding to random state:  60 is:  0.3354327339233778
r2 score corresponding to random state:  61 is:  0.31538662723157607
r2 score corresponding to random state:  62 is:  0.14058683003826
r2 score corresponding to random state:  63 is:  0.7248249465014855
r2 score corresponding to random state:  64 is:  0.4327089335136115
r2 score corresponding to random state:  65 is:  0.3494113433601709
r2 score corresponding to random state:  66 is:  -0.027995378121945746
r2 score corresponding to random state:  67 is:  0.02472332374371955
r2 score corresponding to random state:  68 is:  0.20170937807837208
r2 score corresponding to random state:  69 is:  0.22165518875772228
r2 score corresponding to random state:  70 is:  0.15430507815290218
r2 score corresponding to random state:  71 is:  0.7639876272736552
r2 score corresponding to random state:  72 is:  0.3883670143418685
r2 score corresponding to random state:  73 is:  0.3882697719947108
r2 score corresponding to random state:  74 is:  0.223206149819849
r2 score corresponding to random state:  75 is:  0.38936453350481814
r2 score corresponding to random state:  76 is:  0.37100100507457734
r2 score corresponding to random state:  77 is:  -0.16803733183819713
r2 score corresponding to random state:  78 is:  0.4549145546747625
r2 score corresponding to random state:  79 is:  0.3471487364304595
r2 score corresponding to random state:  80 is:  0.4194176334188985
r2 score corresponding to random state:  81 is:  -1.1816363725138777
r2 score corresponding to random state:  82 is:  0.45576961017311957
r2 score corresponding to random state:  83 is:  0.5528137149704344
r2 score corresponding to random state:  84 is:  0.06781021442415847
r2 score corresponding to random state:  85 is:  0.5135768842864206
r2 score corresponding to random state:  86 is:  0.6722087087748213
r2 score corresponding to random state:  87 is:  0.4439665614132099
r2 score corresponding to random state:  88 is:  -2.7916712171440263
r2 score corresponding to random state:  89 is:  0.5431273809293296
r2 score corresponding to random state:  90 is:  0.4479028349257649
r2 score corresponding to random state:  91 is:  -0.08118571608630787
r2 score corresponding to random state:  92 is:  0.38122965930042807
r2 score corresponding to random state:  93 is:  0.4956987508538404
r2 score corresponding to random state:  94 is:  0.7775301851333121
r2 score corresponding to random state:  95 is:  -1.0272758002714668
r2 score corresponding to random state:  96 is:  0.022439432987762742
r2 score corresponding to random state:  97 is:  0.416768536586807
r2 score corresponding to random state:  98 is:  0.21341864438362024
r2 score corresponding to random state:  99 is:  0.40296569040611074
max r2 score corresponding to 94  is  0.7775301851333121

In [18]:
print("Mean r2score for Lasso Regression: ",cross_val_score(lsreg,x,y,cv=10,scoring="r2").mean())
print("Standard deviation in r2 score for Lasso Regression: ",cross_val_score(lsreg,x,y,cv=5,scoring="r2").std())

Mean r2score for Lasso Regression:  -17.25465546566855
Standard deviation in r2 score for Lasso Regression:  0.5373760279412259

In [19]:
from sklearn.ensemble import GradientBoostingRegressor
import warnings
warnings.filterwarnings("ignore")
gbr=GradientBoostingRegressor()
parameters={"learning_rate":[0.001,0.01,0.1,1],"n_estimators":[10,100,500,1000]}
ggbr = GridSearchCV(gbr, parameters, cv=5)
ggbr.fit(x,y)
ggbr.best_params_

{'learning_rate': 0.001, 'n_estimators': 100}

In [20]:
gbr=GradientBoostingRegressor(learning_rate=0.001,n_estimators=100)
print("Mean r2score for gradient boosting Regression: ",cross_val_score(gbr,x,y,cv=5,scoring="r2").mean())
print("Standard deviation in r2 score for Gradient Boosting Regression: ",cross_val_score(gbr,x,y,cv=5,scoring="r2").std())

Mean r2score for gradient boosting Regression:  -0.4387047417384249
Standard deviation in r2 score for Gradient Boosting Regression:  0.258542098396693

In [21]:
r_state=maxr2_score(gbr,x,y)

r2 score corresponding to random state:  42 is:  0.04662790722205323
r2 score corresponding to random state:  43 is:  -0.2184449901988128
r2 score corresponding to random state:  44 is:  0.06723047921360736
r2 score corresponding to random state:  45 is:  -0.3215154165841536
r2 score corresponding to random state:  46 is:  -0.058329605290211584
r2 score corresponding to random state:  47 is:  0.09402998167589194
r2 score corresponding to random state:  48 is:  0.03849022479116926
r2 score corresponding to random state:  49 is:  0.05329159509391146
r2 score corresponding to random state:  50 is:  -0.08326446435458124
r2 score corresponding to random state:  51 is:  -0.8441160914019776
r2 score corresponding to random state:  52 is:  -0.445205567094094
r2 score corresponding to random state:  53 is:  -1.4881560912575464
r2 score corresponding to random state:  54 is:  0.10437954859724641
r2 score corresponding to random state:  55 is:  -0.13463770114159979
r2 score corresponding to random state:  56 is:  0.07940002483982267
r2 score corresponding to random state:  57 is:  -0.6313539346373149
r2 score corresponding to random state:  58 is:  -1.210622147794108
r2 score corresponding to random state:  59 is:  0.05104153106381193
r2 score corresponding to random state:  60 is:  0.026413539140387243
r2 score corresponding to random state:  61 is:  0.04356285999550835
r2 score corresponding to random state:  62 is:  -0.25676651716163557
r2 score corresponding to random state:  63 is:  0.14886169904199764
r2 score corresponding to random state:  64 is:  -0.11481541512468452
r2 score corresponding to random state:  65 is:  -0.052211404994469746
r2 score corresponding to random state:  66 is:  -0.08217911336411543
r2 score corresponding to random state:  67 is:  -0.34709387127589886
r2 score corresponding to random state:  68 is:  -0.01835342882034907
r2 score corresponding to random state:  69 is:  0.02191240252698723
r2 score corresponding to random state:  70 is:  0.045754428882663345
r2 score corresponding to random state:  71 is:  0.21909746124562846
r2 score corresponding to random state:  72 is:  0.06838565353112991
r2 score corresponding to random state:  73 is:  0.07230214758877307
r2 score corresponding to random state:  74 is:  -0.23259282338753118
r2 score corresponding to random state:  75 is:  -0.032697341772762956
r2 score corresponding to random state:  76 is:  0.07043551097192946
r2 score corresponding to random state:  77 is:  -0.16759997824275819
r2 score corresponding to random state:  78 is:  0.11296007269964059
r2 score corresponding to random state:  79 is:  0.004721991681276738
r2 score corresponding to random state:  80 is:  0.1088159080785992
r2 score corresponding to random state:  81 is:  -0.8968027669065395
r2 score corresponding to random state:  82 is:  0.11175501213099859
r2 score corresponding to random state:  83 is:  0.07493957480691882
r2 score corresponding to random state:  84 is:  -0.26314198460484106
r2 score corresponding to random state:  85 is:  0.0951077793853804
r2 score corresponding to random state:  86 is:  -0.01334288499807501
r2 score corresponding to random state:  87 is:  0.03616189823330995
r2 score corresponding to random state:  88 is:  -6.075608051561421
r2 score corresponding to random state:  89 is:  0.1629404959596834
r2 score corresponding to random state:  90 is:  0.06590752753335372
r2 score corresponding to random state:  91 is:  -0.3303223131085604
r2 score corresponding to random state:  92 is:  -0.046548395842981094
r2 score corresponding to random state:  93 is:  0.11194319159678368
r2 score corresponding to random state:  94 is:  0.1898071162023044
r2 score corresponding to random state:  95 is:  -2.0124609845655774
r2 score corresponding to random state:  96 is:  -0.4045998963311479
r2 score corresponding to random state:  97 is:  0.12361034715750119
r2 score corresponding to random state:  98 is:  -0.015840573491431975
r2 score corresponding to random state:  99 is:  0.07697012768324296
max r2 score corresponding to 71  is  0.21909746124562846

In [22]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
ada_reg=AdaBoostRegressor()
parameters={"learning_rate":[0.001,0.01,0.1,1],"n_estimators":[10,100,500,1000],"base_estimator":[lreg,lsreg,DecisionTreeRegressor()]}
gada = GridSearchCV(ada_reg, parameters, cv=5)
gada.fit(x,y)
gada.best_params_

{'base_estimator': LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
 'learning_rate': 0.001,
 'n_estimators': 1000}

In [26]:
ada_reg=AdaBoostRegressor(learning_rate=0.001,n_estimators=1000)
print("Mean r2score for Ada boosting Regression: ",cross_val_score(ada_reg,x,y,cv=5,scoring="r2").mean())
print("Standard deviation in r2 score for Ada Boosting Regression: ",cross_val_score(ada_reg,x,y,cv=5,scoring="r2").std())

Mean r2score for Ada boosting Regression:  -1.2621557495286069
Standard deviation in r2 score for Ada Boosting Regression:  3.1305799003621817

In [27]:
r_state=maxr2_score(ada_reg,x,y)

r2 score corresponding to random state:  42 is:  0.6364684155274943
r2 score corresponding to random state:  43 is:  -0.8598641210870319
r2 score corresponding to random state:  44 is:  0.6000977034649477
r2 score corresponding to random state:  45 is:  0.3734439416792361
r2 score corresponding to random state:  46 is:  0.4279287703939515
r2 score corresponding to random state:  47 is:  0.6252378490950496
r2 score corresponding to random state:  48 is:  0.749967997951869
r2 score corresponding to random state:  49 is:  0.55372974980272
r2 score corresponding to random state:  50 is:  0.6291452778469973
r2 score corresponding to random state:  51 is:  -0.12933140933140908
r2 score corresponding to random state:  52 is:  -0.061748209217461936
r2 score corresponding to random state:  53 is:  -0.24036777583187385
r2 score corresponding to random state:  54 is:  0.703193057798659
r2 score corresponding to random state:  55 is:  0.41337527670977503
r2 score corresponding to random state:  56 is:  0.46788916055419705
r2 score corresponding to random state:  57 is:  0.3166956765861877
r2 score corresponding to random state:  58 is:  -0.20972812358917392
r2 score corresponding to random state:  59 is:  -0.6644650993256787
r2 score corresponding to random state:  60 is:  0.5525776185602183
r2 score corresponding to random state:  61 is:  0.374506458394649
r2 score corresponding to random state:  62 is:  0.22293722293722307
r2 score corresponding to random state:  63 is:  -0.06549361407881715
r2 score corresponding to random state:  64 is:  0.3379884313217646
r2 score corresponding to random state:  65 is:  0.6527321088674949
r2 score corresponding to random state:  66 is:  -0.46347096932464993
r2 score corresponding to random state:  67 is:  0.34821457301133407
r2 score corresponding to random state:  68 is:  0.1115181646005512
r2 score corresponding to random state:  69 is:  0.5591276750090679
r2 score corresponding to random state:  70 is:  -1.331781774051192
r2 score corresponding to random state:  71 is:  0.5965168022096059
r2 score corresponding to random state:  72 is:  0.570990185358742
r2 score corresponding to random state:  73 is:  0.6985089268579443
r2 score corresponding to random state:  74 is:  0.3931032878411914
r2 score corresponding to random state:  75 is:  0.4916691305581584
r2 score corresponding to random state:  76 is:  0.5331475591858
r2 score corresponding to random state:  77 is:  -1.3642782738095232
r2 score corresponding to random state:  78 is:  0.2800659057078866
r2 score corresponding to random state:  79 is:  0.4207795355445155
r2 score corresponding to random state:  80 is:  0.6073950722790584
r2 score corresponding to random state:  81 is:  -6.681591836734694
r2 score corresponding to random state:  82 is:  0.6815038372328335
r2 score corresponding to random state:  83 is:  0.4239653354422036
r2 score corresponding to random state:  84 is:  0.5372031497007679
r2 score corresponding to random state:  85 is:  0.3946281943774841
r2 score corresponding to random state:  86 is:  0.123206845238095
r2 score corresponding to random state:  87 is:  0.4980682549903409
r2 score corresponding to random state:  88 is:  -2.9109374993177366
r2 score corresponding to random state:  89 is:  -0.09405335974052087
r2 score corresponding to random state:  90 is:  0.3790787172011658
r2 score corresponding to random state:  91 is:  0.2593883501276266
r2 score corresponding to random state:  92 is:  0.6649292818687838
r2 score corresponding to random state:  93 is:  0.633733263272614
r2 score corresponding to random state:  94 is:  -0.04742424242424281
r2 score corresponding to random state:  95 is:  -0.08147094421939616
r2 score corresponding to random state:  96 is:  0.20898100907029504
r2 score corresponding to random state:  97 is:  0.686017800746483
r2 score corresponding to random state:  98 is:  0.2530297581206673
r2 score corresponding to random state:  99 is:  0.8077711708017223
max r2 score corresponding to 99  is  0.8077711708017223

# Model Selection

In [ ]:
I choose LinearRegression Model as my preferred model as it performs better on the above dataset.

# Save the Model

In [ ]:
from sklearn.externals import joblib

In [ ]:
joblib.dump(lreg,'Model_Baseballset.csv')